language: cpp
sudo: required
dist: precise

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.9

    - compiler: gcc
      env: COMPILER=g++-5

    - compiler: clang
      env: COMPILER=clang++-3.6

    - compiler: clang
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev

script:
  - cd Codes-Yche
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ../src
  - make
  - ./CISAlgo 1 ../demo_input_files/collaboration_edges_input.csv
  - ./CISAlgo 8 ../demo_input_files/collaboration_edges_input.csv
  - ./DemonAlgo 1 ../demo_input_files/collaboration_edges_input.csv
  - ./DemonAlgo 8 ../demo_input_files/collaboration_edges_input.csv
